# Generated by Django 6.0.3 on 2026-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_record_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='validity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_validity',
            field=models.BooleanField(default=True),
        ),
    ]
