# Generated by Django 6.0.3 on 2026-04-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_user_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='validity',
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Friend', 'Friend'), ('Business', 'Business'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Groceries', 'Groceries'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=100),
        ),
    ]
