# Generated by Django 6.0.3 on 2026-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_record_validity_alter_record_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
